services:
  mongodb:
    container_name: mongodb
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongodb_data_container:/data/db

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongodb"
      MONGODB_DATABASE_NAME: "somedb"


volumes:
  mongodb_data_container: